### ISSUE TITLE
how to inference and visualize on image?

### ISSUE THREAD

**Issue by jinfagang** [megvii-research/SOLQ#3]
how to inference and visualize on image?

**Comment by dbofseuofhust** [comment]
> how to inference and visualize on image?

Thanks for your attention, we now upload `visual.py` as https://github.com/megvii-research/SOLQ/blob/main/visual.py

**Comment by jinfagang** [comment]
```
loaded ./weights/solq_r50_final.pth
Drop parameter transformer.decoder.bbox_embed.0.layers.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.0.layers.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.0.layers.1.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.0.layers.1.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.0.layers.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.0.layers.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.1.layers.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.1.layers.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.1.layers.1.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.1.layers.1.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.1.layers.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.1.layers.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.2.layers.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.2.layers.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.2.layers.1.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.2.layers.1.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.2.layers.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.2.layers.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.3.layers.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.3.layers.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.3.layers.1.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.3.layers.1.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.3.layers.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.3.layers.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.4.layers.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.4.layers.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.4.layers.1.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.4.layers.1.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.4.layers.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.4.layers.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.5.layers.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.5.layers.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.5.layers.1.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.5.layers.1.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.5.layers.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter transformer.decoder.bbox_embed.5.layers.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.0.layers.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.0.layers.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.0.layers.1.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.0.layers.1.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.0.layers.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.0.layers.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.1.layers.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.1.layers.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.1.layers.1.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.1.layers.1.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.1.layers.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.1.layers.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.2.layers.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.2.layers.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.2.layers.1.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.2.layers.1.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.2.layers.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.2.layers.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.3.layers.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.3.layers.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.3.layers.1.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.3.layers.1.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.3.layers.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.3.layers.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.4.layers.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.4.layers.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.4.layers.1.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.4.layers.1.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.4.layers.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.4.layers.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.5.layers.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.5.layers.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.5.layers.1.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.5.layers.1.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.5.layers.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
Drop parameter vector_embed.5.layers.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.
  0%|                                                                                                                                                  | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "visual.py", line 223, in <module>
    det.detect(vis=True)
  File "visual.py", line 180, in detect
    outputs = self.detr(cur_img.cuda().float())
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)

```
